Add support for building/installing xPL_Hub
Before we can really enable xPL support in Heyu, our build system,
in cooperation with our custom /Configure.sh script, must be capable
of setting up a complete runtime environment required to run Heyu
successfully, or at least displaying warnings if complete setup is not
possible. An important element of such an environment is a running xPL
hub.

Extend the Heyu build system with rules for conditionally (or manually)
building and installing an example xPL_Hub daemon provided by xPLLib
sources. Reuse the ./configure --enable-postinst option for activating
this extra functionality in 'make' and 'make install'.

Signed-off-by: Janusz Krzysztofik <jkrzyszt@tis.icnet.pl>

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -36,6 +36,11 @@ nodist_libxPL_a_SOURCES = $(xPLLib_srcdir)/xPL-config.c $(xPLLib_srcdir)/xPL.h \
 	$(xPLLib_srcdir)/xPL-listeners.c $(xPLLib_srcdir)/xPL-message.c \
 	$(xPLLib_srcdir)/xPL_priv.h $(xPLLib_srcdir)/xPL-service.c \
 	$(xPLLib_srcdir)/xPL-store.c $(xPLLib_srcdir)/xPL-utils.c
+EXTRA_PROGRAMS = xPL_Hub
+nodist_xPL_Hub_SOURCES = $(xPLLib_srcdir)/examples/xPL_Hub.c
+xPL_Hub_DEPENDENCIES = libxPL.a
+xPL_Hub_LDADD = libxPL.a
+CLEANFILES = xPL_Hub stamp-xPL_Hub
 endif
 dist_man_MANS = heyu.1 x10config.5 x10sched.5 x10scripts.5 x10cm17a.5 x10aux.5 \
 	x10rfxsensors.5 x10rfxmeters.5 x10digimax.5 x10oregon.5 x10kaku.5
@@ -50,7 +55,7 @@ EXTRA_DIST = Configure.sh post-install.sh
 *.o: Makefile
 
 if XPLLIB_ARCHIVE
-$(nodist_libxPL_a_SOURCES): $(xPLLib_archive)
+$(nodist_libxPL_a_SOURCES) $(nodist_xPL_Hub_SOURCES): $(xPLLib_archive)
 	@mkdir -p "$(xPLLib_srcdir)"
 	@case "$<" in \
 	*.tar.gz|*.tgz) GZIP=$(GZIP_ENV) gzip -dc "$<" | \
@@ -77,7 +82,34 @@ $(xPLLib_archive):
 endif
 
 if POSTINST
+if XPLLIB_SRCDIR
+all-local: stamp-xPL_Hub usergroup.tmp userhome.tmp
+
+stamp-xPL_Hub: $(nodist_xPL_Hub_SOURCES) Makefile
+	@if netstat -uln 2>/dev/null | grep -q ":3865 " ||\
+			type xPL_Hub$(EXEEXT) 2>/dev/null ||\
+			type xplhub.pl 2>/dev/null ||\
+			type xPLHub.jar 2>/dev/null; then \
+		rm -f xPL_Hub$(EXEEXT);\
+	elif $(MAKE) $(AM_MAKEFLAGS) xPL_Hub; then \
+	echo "";\
+	echo "An xPL hub daemon, required for running Heyu built with xPL";\
+	echo "suppport enabled, has been additionally compiled for you, and";\
+	echo "will be installed along with the Heyu binary upon executing";\
+	echo "'make install', unless a running xPL hub is detected by then.";\
+	echo "";\
+	echo "If this is not what you want, i.e., you have an xPL hub already";\
+	echo "installed in your system and don't want to install another one,";\
+	echo "please remove the xPL_Hub executable from the current directory";\
+	echo "before proceeding with 'make install'.";\
+	echo "";\
+	echo "If removed, it can be rebuilt with 'make xPL_Hub'.";\
+	echo "";\
+	fi
+	@touch $@
+else
 all-local: usergroup.tmp userhome.tmp
+endif
 
 usergroup.tmp userhome.tmp: $(bin_PROGRAMS)
 	@echo `id` >usergroup.tmp
@@ -89,4 +121,41 @@ usergroup.tmp userhome.tmp: $(bin_PROGRAMS)
 install-exec-hook:
 	@$(POST_INSTALL)
 	@POSTINST@
+if XPLLIB_SRCDIR
+	@if ! netstat -uln|grep -q ":3865 " && test -x xPL_Hub$(EXEEXT);then \
+		$(MAKE) $(AM_MAKEFLAGS) bin_PROGRAMS=xPL_Hub$(EXEEXT) \
+				install-binPROGRAMS; fi
+
+install-data-hook:
+	@if netstat -uln|grep -q ":3865 " || test -x xPL_Hub$(EXEEXT); then :;\
+	else \
+	echo "";\
+	echo "Heyu has been built with xPL support enabled, and it requires";\
+	echo "an xPL hub daemon running before it can be used.";\
+	echo "";\
+	echo "If you have an xPL hub already installed in your system, please";\
+	echo "start it up before running Heyu.  If you don't have one, please";\
+	echo "see http://xplproject.org.uk/wiki/index.php?title=Core_Software";\
+	echo "for possible options.";\
+	echo;\
+	echo "Please also set up the hub for being started on boot, before";\
+	echo "Heyu is run.";\
+	echo;\
+	echo "You can also relay on Heyu starting the hub automatically for";\
+	echo "you if you choose one of Heyu known xPL hubs, and its binary";\
+	echo "can be found in your \$$PATH.  The xPL hubs known to Heyu are:";\
+	echo "* xPL_Hub   - see http://www.xpl4java.org/xPL4Linux/,";\
+	echo "* xplhub.pl - see http://johnb.xplproject.org.uk/info/perl/.";\
+	echo;\
+	echo "Another example of a hub that can be started automatically by";\
+	echo "Heyu, but only if your system is configured for directly";\
+	echo "running Java executables found in your \$$PATH, is xPLHub.jar,";\
+	echo "which can be downloaded from http://www.xpl4java.org/xPL4Java/.";\
+	echo "";\
+	echo "Finally, you can set up Heyu to start up any hub of your choice";\
+	echo "by providing its command name and arguments in your x10config.";\
+	echo "See 'man x10config' for details.";\
+	echo "";\
+	fi
+endif
 endif
